### ISSUE TITLE
Auto-fetch new inputs

### ISSUE THREAD

**Issue by proegssilb** [proegssilb/ferris-elf#12]
The bot has about 60 seconds after puzzle release to get the inputs it needs to benchmarks before the fastest of the fastest people in the world start submitting solutions to AOC.

There's a script to fetch new inputs. We should automate that. And then document how to set up that automation.

**Comment by ankitson** [comment]
We should be able to use [aoc-cli](https://github.com/scarvalhojr/aoc-cli/) for this. I use it on my own repo [here](https://github.com/ankitson/aoc/blob/main/2023/justfile#L1) and it works well:

**Comment by proegssilb** [comment]
I do like the feature list of aoc-cli. If we can easily integrate it with the bot's existing config (so that the bot owner doesn't have to configure two different things), then I'm open to proposals. I will say, there can be some concern with how secrets are passed between programs, but I'd imagine there are workarounds if we can't get aoc-cli to read the bot's config file.

I will note this is a v0.1 issue. Don't let "perfect" be the enemy of "good". If it's too hard to get aoc-cli integrated, figure out a systemd timer file for the fetch script, and we'll figure out the rest of it later.
