### ISSUE TITLE
Review available crates

### ISSUE THREAD

**Issue by proegssilb** [proegssilb/ferris-elf#9]
The list of currently available crates is limited. Rust Playground allows the top 100 by downloads. We should figure out a policy that works for the Discord server.

The current state is that most of the code submitted will have to be crate-free. That's a fine place to start, but it is limiting.

**Comment by ultrabear** [comment]
We have 3 options from here:
- Allow arbitrary crates (up to a sanity limit)
- Allow crates that we vetted and tagged, cargo-vet might help if we include it in our deployment
- Continue to not allow crates

Obviously, not being able to use custom crates holds people back from submitting their solutions altogether, or makes them hack around some functionality they were depending on a library for, so we want to allow external crates

Ideally we just allow arbitrary crates up to a sanity limit, and put a cap on the build time too, this requires storing the "usercrates" that the user specifies somehow and placing it into the benching crate somehow

**Comment by ultrabear** [comment]
The easiest way would probably be making our image have the benching crate premade with a bunch of crates we vetted preinstalled, just with a dummy solution.rs file
and then when we spawn a container, we swap the solution.rs with their input file, add their crates that we dont already have to the Cargo.toml, build, pause as we add the inputs to the docker, and then run the system
We should also make sure the container has no networking so they cant just cheat out the inputs we use with a web crate

**Comment by ultrabear** [comment]
Since our list of prevetted crates may change, we should also store the "vetted crate list version number" with the user submission, and avoid any crates that are happy to break in new versions, leaving our system either out of date or unable to build old submissions

**Comment by proegssilb** [comment]
Doesn't Rust Playground allow requesting crates via a comment in the code or something? If we can do something similar, that doesn't sound horrible to me? Oh, but wait, we're file input, not text-blob input. Hmm. We'll have to think about that a bit; there could be a UX issue hiding in here.

@ankitson , do you know anything about a method to pull code out of a crate and into a file? Something about a tool competitive coders use?

I'm down with microbench. People use that, it's just not popular. But I honestly would be hesitant to put my own AOC Runner Macros on the allowed list. It's something only I use. I'd rather have to strip out the macros semi-regularly, or figure out a non-macro solution. That's just me, though.

Open to proposals, I just wanted to get my concerns out there, get some options on the table. If there's a way to make this work securely, I'm happy to hear it.

**Comment by ankitson** [comment]
@proegssilb Yes, here is [cargo-equip](https://github.com/qryxip/cargo-equip) that is apparently used by competitive programmers because those sites generally accept a single file submission. I have not used it myself but it looks pretty good.

**Comment by proegssilb** [comment]
Last time I did a test run, I could have sworn the bot downloaded crates. Will need to re-test that before closing this.

**Comment by proegssilb** [comment]
I started a branch for using `cargo vet` to allow any vetted crate to be OK. We have too many crates that would require trusting specific individuals, rather than a statement certifying the crate, in order for me to be comfortable taking on the workload of going through our dependencies in detail looking for stuff.

Here's the branch: https://github.com/proegssilb/ferris-elf/tree/cargo-vet

If someone wants to take that work on, great. Otherwise, I'm just going to figure out how to swipe Rust Playground's list of crates and move on.
